# Generated by Django 5.1.1 on 2024-09-11 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
