# Generated by Django 5.1.1 on 2024-10-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_manager', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
    ]
