# Generated by Django 5.1.1 on 2024-12-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_manager', '0005_alter_event_liga_alter_event_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('O', 'On Going')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='liga',
            name='description',
            field=models.CharField(default=models.CharField(max_length=35, unique=True), max_length=255),
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.CharField(default=models.CharField(max_length=35, unique=True), max_length=255),
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
