# Generated by Django 5.1.1 on 2024-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_manager', '0006_event_period_event_status_liga_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liga',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
